### ISSUE TITLE
off-the-shelf system to estimate hand articulation θA

### ISSUE THREAD

**Issue by anilesec** [JudyYe/ihoi#1]
Hi @JudyYe 

I read the paper, its a very cool idea. Thanks for making the code available.
I have a question regarding the off-the-shelf system to estimate hand articulation θA. Is this hand articulation  **"θA"** (of dim 45) is MANO PCA/Axis-angle parameters?

Does this mean that  off-the-shelf system provides mano parameters and camera pose as output?

Thanks in advance!

Looking forward to hearing from you

**Comment by JudyYe** [comment]
Hi 

Thank you for reaching out. 

theta_A is MANO pose parameter minus wrist orientation, i.e. the last 45 dim for 15 joints from 48 dim (15joints+wrist). 

Yes. The off-the-shelf system provides mano parameters with a camera pose. The camera is a weak perspective camera parameterized by (s, tx, ty)

**Comment by anilesec** [comment]
Hi @JudyYe 

Thanks for the answer!

I am curious :) How accurate is this weak perspective camera or the converted full perspective camera? Was it accurate enough to project the hand and object accurately on to image? Is there any evaluation on estimated/converted camera poses?

Thank you in advance!

**Comment by JudyYe** [comment]
Hi, 

Thank you for your question. I would say the frankmocap camera is quite good! We did not evaluate it quantitatively but the human hand pose estimation reports numbers. Qualitatively, here is me firing [FrankMocap](https://github.com/facebookresearch/frankmocap/) on arbitrary images from [100DOH](https://fouheylab.eecs.umich.edu/~dandans/projects/100DOH/). 

<img width="2854" alt="image" src="https://user-images.githubusercontent.com/12457136/167653932-bd62e812-e276-4368-9fb6-93a7c67f56e2.png">
