### ISSUE TITLE
Problems for dataset preparation

### ISSUE THREAD

**Issue by ZhangCYG** [JudyYe/ihoi#10]
Hello, could you please tell me how to prepare the obman and ho3d dataset according to your preprocess.md? I did not find the official link of obman containing 'obmanobj' folder. What I've downloaded consists of 'obman', 'shapenet_grasps' and 'bodywithands' folder. Meanwhile, I also did not find the official link of ho3d containing 'ho3dobj' folder, but only had 'evaluation' and 'train' folder.

**Comment by Hojan-Ye** [comment]
I have the same problem. Have you solve this?

**Comment by dqj5182** [comment]
Same question

**Comment by JudyYe** [comment]
Hi ZhangCGY, Thank you for your interest, and sorry for the late response. We've discussed it via email but I'm marking down the clarifications. 

`obmanobj` and `ho3dobj` are soft links to the object CAD repo used in each dataset. `obmanobj` is ObMan dataset that uses ShapeNetCore.v2, while `ho3dobj` is the HO3D dataset that uses YCB objects. 

Sorry for the confusion.
