### ISSUE TITLE
HO3D metafiles

### ISSUE THREAD

**Issue by hongsukchoi** [JudyYe/ihoi#11]
Where can I find HO3D `meta_gt` and `meta_plus` pkl files? I want to evaluate with estimated 3D hand meshes. And is this repo using HO3D_v3? not v2? 

Thank you!

**Comment by hongsukchoi** [comment]
I think `meta_plus` pkl files are the outputs from FrankMocap, but the evaluation results were different from the paper, so I was confused.

**Comment by hongsukchoi** [comment]
And this repo is using HO3D_v3. I hope others can refer to this!

**Comment by JudyYe** [comment]
Hi Hongsuk,

Sorry for replying late. I don't have `meta_plus` any more. but I believe they are in the cache provided here: https://drive.google.com/drive/u/1/folders/1v6Pw6vrOGIg6HUEHMVhAQsn-JLBWSHWu
