### ISSUE TITLE
How can I find hparams.yaml file?

### ISSUE THREAD

**Issue by dqj5182** [JudyYe/ihoi#12]
I am trying to run the demo but the code gives error "FileNotFoundError: [Errno 2] No such file or directory: 'ihoi/weights/hparams.yaml'".

Could you upload the hparams.yaml file?

**Comment by JudyYe** [comment]
Hi, Thanks for your interest. They are in the [pretrained model](https://github.com/JudyYe/ihoi/blob/main/scripts/download_models.sh) we have provided. Please follow the [instructions](https://github.com/JudyYe/ihoi/blob/main/docs/preprocess.md) to preprocess data.
