### ISSUE TITLE
Which images from MOW dataset did IHOI used for training?

### ISSUE THREAD

**Issue by dqj5182** [JudyYe/ihoi#14]
In the paper, it claims that "We use 350 randomly selected examples for training and the remaining 92 for evaluation". I cannot figure out which 350 randomly samples out of 512 publicly available samples of MOW dataset were used for training?

**Comment by JudyYe** [comment]
Hi,
Thank you for your interest! The list can be found at the preprocessed data provided [here](https://drive.google.com/drive/folders/1v6Pw6vrOGIg6HUEHMVhAQsn-JLBWSHWu). `rhoi_train.pkl` and `rhoi_test.pkl` are dict with image index as keys. 

For your convenience, here is a split list we used. 

[rhoi_split.json](https://github.com/JudyYe/ihoi/files/13816828/rhoi_split.json)
