### ISSUE TITLE
Normalized wrist coordinate frame

### ISSUE THREAD

**Issue by anilesec** [JudyYe/ihoi#2]
Hi @JudyYe ,

What is a normalized wrist coordinate frame? 
Is it the coordinate frame centred around the wrist location off-the-shelf hand estimate? In other words, do you create a grid that is centred around the wrist location that is obtained from an off-the-shelf hand estimator(frankmocap)?

Which are off-the-shelf hand estimators used?

**Comment by JudyYe** [comment]
Hi, 

Thank you for your question. 

The normalized wrist frame is the hand pose without wrist orientation, e.g. the palm always face up. The origin is placed on top of an open palm.  

The off-the-shelf hand estimator is [frankmocap](https://github.com/facebookresearch/frankmocap).

**Comment by anilesec** [comment]
Hi @JudyYe 

Thanks for your response.
"Normalized wrist frame" is the hand pose without wrist orientation. Okay, what about the fingers? Because in Figure2(in the paper), the hand is facing upwards without any orientation. 

Does it mean that you consider the template hand pose(palm always face up) and place the coord frame on top of open palm and then learn the shape of the object in this one fixed frame for all the input images? 

Also, how much above the palm do you place the origin?

Would you please provide intuition for this technique? How different is this from learning the object shape in a general normalized frame with origin as (0,0,0) in the camera frame itself?

Thank you in Advance!

**Comment by JudyYe** [comment]
Hi, 

Thank you for such a good question! 
What you understand is correct. No matter what the hand appears in the image, we always undo the wrist orientation and convert it to a palm-up (normalized) frame. The intuition is that when one holds the object and rotate its wrist, the relative position between hand and object change less than in camera frame. Hence it's easier for the network to learn.

wrist frame | camera frame
--- | ---
![hhoi](https://user-images.githubusercontent.com/12457136/167653183-e487cb51-96b4-4c30-b4f7-25de40529658.gif) |  ![choi](https://user-images.githubusercontent.com/12457136/167652875-47017407-dee4-48f7-949e-fe8e31ff4d5d.gif)

**Comment by anilesec** [comment]
Hi @JudyYe 

Thank you very much for the explanation!

Q1: Why do we need to undo the wrist orientation to convert to palm-up? Since its a palm up after undoing the wrist orientation, why can't we just consider one default palm-up hand and learn the shape on this(default palm-up) fixed coord frame for all input images? In other words, what is the difference between the palm-up(normalized frame) you obtain for each different input image?

Q2: Thanks for the intuition! But this intuition holds good only when you have used video sequences in your training, Right?
Also, is there any quantitative analysis to observe the positive aspect of learning in normalized frame?

Thanks in Advance! I deeply appreciate you for taking time to answer my questions :)

**Comment by dqj5182** [comment]
May I ask how you visualized under palm-up (normalized) frame?
