### ISSUE TITLE
the wrong hyperlink in the paper

### ISSUE THREAD

**Issue by hongsukchoi** [JudyYe/ihoi#3]
Hi, I met you at the CVPR.

I just wanted to tell you that the [Camera ready version's](https://openaccess.thecvf.com/content/CVPR2022/papers/Ye_Whats_in_Your_Hands_3D_Reconstruction_of_Generic_Objects_in_CVPR_2022_paper.pdf) code link connect to the wrong repo: https://judyye.github.io/ShSMesh/.

**Comment by JudyYe** [comment]
Hi Hongsuk,

Thank you for reaching out! That is a very unfortunate mistake of me :/ I cannot modify the version on CVF anymore. I'll check the arxiv version make it more careful next time. Thank you!
