### ISSUE TITLE
How long to evaluate the model?

### ISSUE THREAD

**Issue by Branish233** [JudyYe/ihoi#4]
hello, very valuable work! 

I evaluate the model directly by using this command:  
"python -m models.ihoi   --eval --ckpt ./release_model/obman/checkpoints/last.ckpt  --slurm "
but i find it is very time costing. It takes 2 hrs to evaluate the model. 

Testing: 100%|??????????| 786/786 [2:21:50<00:00, 10.83s/it] 

I run the program in gpu, 1080ti 10GB. Is it normal for this model? 
By the way, I want to know how long to train this model on obaman. 
THX

**Comment by JudyYe** [comment]
Hi, 

I cannot recall the exact evaluation time. But the evaluation is in general not quick as the cost is mainly from the marching cube algorithm as we need to sample N**3 points -- the same reason for volumetric rendering is slow. 
We train the model with 8 GPUs on obman for approximately one day.
