### ISSUE TITLE
Eikonal loss in the code

### ISSUE THREAD

**Issue by ap229997** [JudyYe/ihoi#6]
Where is the eikonal loss term implemented in the code? I can't find it in `models/ihoi.py`.

**Comment by JudyYe** [comment]
Hi, 

The gradient is calculated [here](https://github.com/JudyYe/ihoi/blob/main/models/dec.py#L244), copied from VolSDF.

**Comment by ap229997** [comment]
The function to calculate the gradient exists but the function is not called anywhere, can you please clarify where the eikonal loss is computed in the code
