### ISSUE TITLE
Config for data preprocess using DeepSDF

### ISSUE THREAD

**Issue by ZhangCYG** [JudyYe/ihoi#9]
When using DeepSDF preprocess.py, it requires split.json which i cannot confirm facing the HOI datasets. Could you please provide with the split.json file correspoding to each dataset? Additionally, the parses  DeepSDF preprocess.py needs are also vague to me. Could you please give an example? Thanks a lot!

**Comment by JudyYe** [comment]
Hi ZhangCYG, we have discussed this through email but I am marking down the solution for other's reference. 
1. the split file comes from [`data_cache.tar.gz`](https://drive.google.com/drive/folders/1v6Pw6vrOGIg6HUEHMVhAQsn-JLBWSHWu?usp=sharing). Each file is a dictionary whose keys are data index. 
2. We follow [DeepSDF](https://github.com/facebookresearch/DeepSDF/) preprocess step but only change [this line](https://github.com/facebookresearch/DeepSDF/blob/main/src/PreprocessMesh.cpp#L384) fitToUnitSphere to False.
